export default {
  ON_USER_INPUT: "ON_USER_INPUT",
  ON_LOGIN_SUCCESS: "ON_LOGIN_SUCCESS",
  ON_LOGIN_FAIL: "ON_LOGIN_FAIL",
  ON_LOGOUT_SUCCESS: "ON_LOGOUT_SUCCESS",
  ON_REGISTER_FAIL: "ON_REGISTER_FAIL",
};
